name: Upload Source Files

on:
  push:
    branches:
      - '**'

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload source files
        uses: actions/upload-artifact@v4
        with:
          name: SWJTU_Bachelor_Thesis
          path: |
            appendix/
            bibliography/
            chapters/
            fonts/
            signatures/
            style/
            SWJTU_Bachelor_Thesis.tex
