name: Upload Source Files

on:
  push:
    branches:
      - '**'
    paths:
      - 'appendix/**'
      - 'bibliography/**'
      - 'chapters/**'
      - 'fonts/**'
      - 'signatures/**'
      - 'style/**'
      - 'SWJTU_Bachelor_Thesis.tex'

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >
            scheme-full

      - name: Compile LaTeX (xelatex -> biber -> xelatex*2)
        run: |
          mkdir -p build/appendix build/chapters
          xelatex -synctex=1 -interaction=nonstopmode -file-line-error -output-directory=build SWJTU_Bachelor_Thesis.tex
          biber --output-directory=build SWJTU_Bachelor_Thesis
          xelatex -synctex=1 -interaction=nonstopmode -file-line-error -output-directory=build SWJTU_Bachelor_Thesis.tex
          xelatex -synctex=1 -interaction=nonstopmode -file-line-error -output-directory=build SWJTU_Bachelor_Thesis.tex

      - name: Upload source files
        uses: actions/upload-artifact@v4
        with:
          name: SWJTU_Bachelor_Thesis
          path: |
            appendix/
            bibliography/
            chapters/
            fonts/
            signatures/
            style/
            SWJTU_Bachelor_Thesis.tex

      - name: Upload build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build/SWJTU_Bachelor_Thesis.log
