name: Deploy Start on Overleaf Redirect Page

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Get Latest Release URL
        id: get-latest-release-url
        run: |
          VERSION=$(curl -s https://api.github.com/repos/abwuge/SWJTU_Bachelor_Thesis/releases/latest | jq -r .tag_name)
          ZIP_NAME="SWJTU_Bachelor_Thesis_${VERSION}.zip"
          OVERLEAF_URL="https://www.overleaf.com/docs?snip_uri=https://github.com/abwuge/SWJTU_Bachelor_Thesis/releases/download/${VERSION}/${ZIP_NAME}&main_document=SWJTU_Bachelor_Thesis.tex&engine=xelatex"
          echo "overleafUrl=$OVERLEAF_URL" >> $GITHUB_OUTPUT

      - name: Generate HTML
        run: |
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html>  
          <head>
              <meta http-equiv="refresh" content="0; url=${{ steps.get-latest-release-url.outputs.overleafUrl }}" />
              <title>正在跳转至 Overleaf...</title>
          </head>
          <body>
              <p>正在跳转至 <a href="${{ steps.get-latest-release-url.outputs.overleafUrl }}">Overleaf</a>...</p>
          </body>
          </html>
          EOF

      - name: Create or switch to gh_pages branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin gh_pages || true
          git checkout gh_pages 2>/dev/null || git checkout -b gh_pages

      - name: Commit and Push index.html to gh_pages
        run: |
          git add index.html
          git commit -m "Update index.html for Overleaf redirect" || echo "No changes to commit"
          git push origin gh_pages
